/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(image_inference.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(b39ddd6fde28ff8492f4a3e4bcec592a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iqtlabs/image_inference.h>
// pydoc.h is automatically generated in the build directory
#include <image_inference_pydoc.h>

void bind_image_inference(py::module& m)
{

    using image_inference = ::gr::iqtlabs::image_inference;


    py::class_<image_inference,
               gr::block,
               gr::basic_block,
               std::shared_ptr<image_inference>>(m, "image_inference", D(image_inference))

        .def(py::init(&image_inference::make),
             py::arg("tag"),
             py::arg("vlen"),
             py::arg("x"),
             py::arg("y"),
             py::arg("image_dir"),
             py::arg("convert_alpha"),
             py::arg("norm_alpha"),
             py::arg("norm_beta"),
             py::arg("norm_type"),
             py::arg("colormap"),
             py::arg("interpolation"),
             py::arg("flip"),
             py::arg("min_peak_points"),
             py::arg("model_server"),
             py::arg("model_name"),
             py::arg("confidence"),
             py::arg("max_rows"),
             D(image_inference, make))


        ;
}
