/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(iq_inference.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e9be2dc8c2985cc44c5e04e576515eea)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iqtlabs/iq_inference.h>
// pydoc.h is automatically generated in the build directory
#include <iq_inference_pydoc.h>

void bind_iq_inference(py::module& m)
{

    using iq_inference    = ::gr::iqtlabs::iq_inference;


    py::class_<iq_inference, gr::block, gr::basic_block,
        std::shared_ptr<iq_inference>>(m, "iq_inference", D(iq_inference))

        .def(py::init(&iq_inference::make),
           py::arg("tag"),
           py::arg("vlen"),
           py::arg("n_vlen"),
           py::arg("sample_buffer"),
           py::arg("min_peak_points"),
           py::arg("model_server"),
           py::arg("model_names"),
           py::arg("confidence"),
           py::arg("n_inference"),
           py::arg("samp_rate"),
           py::arg("power_inference"),
           py::arg("background"),
           D(iq_inference,make)
        )
        



        ;




}








