/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tuneable_test_source.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e63c7ab2fcd5d0e0b20127a38cc965fa)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iqtlabs/tuneable_test_source.h>
// pydoc.h is automatically generated in the build directory
#include <tuneable_test_source_pydoc.h>

void bind_tuneable_test_source(py::module& m)
{

    using tuneable_test_source    = ::gr::iqtlabs::tuneable_test_source;


    py::class_<tuneable_test_source, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<tuneable_test_source>>(m, "tuneable_test_source", D(tuneable_test_source))

        .def(py::init(&tuneable_test_source::make),
           py::arg("freq"),
           py::arg("divisor"),
           D(tuneable_test_source,make)
        )
        



        ;




}








