/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vector_roll.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(53c45dbd59ae55c512420c138bed2621)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iqtlabs/vector_roll.h>
// pydoc.h is automatically generated in the build directory
#include <vector_roll_pydoc.h>

void bind_vector_roll(py::module& m)
{

    using vector_roll = ::gr::iqtlabs::vector_roll;


    py::class_<vector_roll,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<vector_roll>>(m, "vector_roll", D(vector_roll))

        .def(py::init(&vector_roll::make), py::arg("vlen"), D(vector_roll, make))


        ;
}
