/*
 * Copyright 2023 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vkfft.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(72d19496ff0525bdb1c0902d4a4d9b08)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iqtlabs/vkfft.h>
// pydoc.h is automatically generated in the build directory
#include <vkfft_pydoc.h>

void bind_vkfft(py::module& m)
{

    using vkfft = ::gr::iqtlabs::vkfft;


    py::class_<vkfft, gr::sync_block, gr::block, gr::basic_block, std::shared_ptr<vkfft>>(
        m, "vkfft", D(vkfft))

        .def(py::init(&vkfft::make), py::arg("vlen"), py::arg("nfft"), D(vkfft, make))


        ;
}
