/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(write_freq_samples.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(68fae4e2419a2f9963bc7cdeeb287190)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/iqtlabs/write_freq_samples.h>
// pydoc.h is automatically generated in the build directory
#include <write_freq_samples_pydoc.h>

void bind_write_freq_samples(py::module& m)
{

    using write_freq_samples    = ::gr::iqtlabs::write_freq_samples;


    py::class_<write_freq_samples, gr::block, gr::basic_block,
        std::shared_ptr<write_freq_samples>>(m, "write_freq_samples", D(write_freq_samples))

        .def(py::init(&write_freq_samples::make),
           py::arg("tag"),
           py::arg("itemsize"),
           py::arg("datatype"),
           py::arg("vlen"),
           py::arg("sdir"),
           py::arg("prefix"),
           py::arg("write_step_samples"),
           py::arg("skip_tune_step_samples"),
           py::arg("samp_rate"),
           py::arg("rotate_secs"),
           py::arg("gain"),
           py::arg("sigmf"),
           py::arg("zstd"),
           py::arg("rotate"),
           D(write_freq_samples,make)
        )
        



        ;




}








