name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-stable
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: Create Shell Env
      run: nix-shell ${GITHUB_WORKSPACE}/.github/workflows/config/test-shell.nix
    - name: build_test 
      run: |
        cppcheck --verbose --language=c++ lib/* && \
        mkdir build && cd build && cmake .. && make && ARGS=--output-on-failure make test && sudo make install && sudo ldconfig && cd .. && \
        cd test_flow_graphs && mkdir test && cd test && testdir=$(pwd) && \
        for g in ../*grc ; do cd $testdir && grcc $g && sed -i 's/output_language: python/output_language: cpp/g' $g && grcc -o test $g ; cd test/*/build && cmake .. && make ; done
