name: nix-test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: run test in nix-shell
      run: |
        nix-shell ${GITHUB_WORKSPACE}/.github/workflows/config/test-shell.nix \
        --command "cppcheck --verbose --language=c++ lib/* && \
        mkdir build && cd build && cmake .. && make && ARGS=--output-on-failure make test && sudo make install && sudo ldconfig && cd .. && \
        cd test_flow_graphs && mkdir test && cd test && testdir=\$(pwd) && \
        export GRC_BLOCKS_PATH=/var/empty/local/share/gnuradio/grc/blocks/ && ln -s /var/empty/local/include/gnuradio/iqtlabs /usr/local/include/gnuradio/iqtlabs && \
        for g in ../*grc ; do cd \$testdir && grcc \$g && sed -i 's/output_language: python/output_language: cpp/g' \$g && grcc -o test \$g ; cd test/*/build && cmake .. && make ; done"
