name: nix-test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install Nix
      uses: cachix/install-nix-action@6a9a9e84a173d90b3ffb42c5ddaf9ea033fad011 # v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - name: run test in nix-shell
      run: |
        nix-shell ${GITHUB_WORKSPACE}/.github/workflows/config/test-shell.nix \
        --command bin/build_test_nix.sh
