name: test

on: [push, pull_request]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: yaml-lint
      uses: ibiqlik/action-yamllint@v3
      with:
        config_data: "{extends: default}"
        file_or_dir: grc/*yml
  test-clang-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: clang-format
      run: |
        sudo apt-get update -yq && sudo apt-get install -yq python3-pip && pip3 install clang-format cmake_format && bin/run_c_format.sh CMakeLists.txt lib include/gnuradio/iqtlabs grc
  test-latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: build_test 
      run: |
        bin/apt_get.sh && TEST_VKFFT=1 bin/build_test.sh && bin/test_grc310.sh
  test-2004-gnuradio39:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: build_test
      # gnuradion 3.9 needs volk 3.0
      run: |
        bin/apt_get.sh && bin/apt_get_39.sh && bin/install-volk.sh v3.0.0 && bin/install-gr39.sh && bin/build_test.sh
  test-2004:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: build_test
      run: |
        sudo apt-get -y update && sudo add-apt-repository ppa:gnuradio/gnuradio-releases && bin/apt_get.sh && bin/install-volk.sh v3.1.2 && TEST_VKFFT=0 bin/build_test.sh && bin/test_grc310.sh
